-- =============================================================================
-- Migration 035: Repair broken subcontractor RLS policies
-- =============================================================================
-- Audit R4-#3. Migration 025 created these policies with two latent bugs:
--
-- 1. `COALESCE(primary_company_id, company_id) FROM users` — `users` has no
--    `company_id` column (only `primary_company_id` was added, in migration
--    011). Postgres name resolution walks out to the outer `subcontractors`
--    row being filtered, so the policy doesn't crash on CREATE, but the
--    semantics are wrong: if any user has a NULL primary_company_id, the
--    policy's IN-list becomes `company_id IN (this_row's_own_company_id)`
--    which is trivially true — the policy leaks ALL subcontractors.
--
-- 2. The `subs_manager_all` and `job_subs_manager_all` policies check
--    `role = 'manager'`, but the role enum was simplified to
--    {owner, office_manager, sales, crew} in a later migration. No row ever
--    has role='manager' anymore, so those policies silently evaluate false.
--
-- On top of both bugs, the whole `auth.uid()`-against-`public.users.id`
-- comparison is non-functional because `public.users.id` is generated by
-- `crypto.randomUUID()` at profile creation time and has no bridge to
-- `auth.users.id` (audit R4-#1, the shared-device Netflix-style model).
-- Server-action layer enforcement is the actual trust boundary.
--
-- Fix: drop the broken policies, replace with the defensive-floor pattern
-- used elsewhere in the codebase (018-023): RLS stays enabled so direct
-- PostgREST access is denied to unauthenticated clients, but enforcement
-- of company scope happens at the server-action layer. This matches the
-- reality of how RoofCRM's auth works and removes the broken SQL.
-- =============================================================================

BEGIN;

-- Drop the broken 025 policies. IF EXISTS is defensive for environments
-- where the policy creation failed mid-migration or was cleaned up manually.
DROP POLICY IF EXISTS "subs_manager_all"     ON public.subcontractors;
DROP POLICY IF EXISTS "subs_read"            ON public.subcontractors;
DROP POLICY IF EXISTS "job_subs_manager_all" ON public.job_subcontractors;
DROP POLICY IF EXISTS "job_subs_read"        ON public.job_subcontractors;

-- Re-create with the defensive-floor pattern. Authenticated users of the
-- Supabase instance (which in practice means Mario's Google identity, via
-- the middleware) can access rows; server actions do the company filter.
CREATE POLICY "subcontractors_authed_all"
  ON public.subcontractors
  FOR ALL
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "job_subcontractors_authed_all"
  ON public.job_subcontractors
  FOR ALL
  USING (auth.uid() IS NOT NULL);

COMMIT;
