-- =============================================================================
-- Migration 036: RLS defensive floor for shared-device auth model
-- =============================================================================
-- Audit R4-#1. Every policy in the codebase that uses
-- `auth.uid() = public.users.id` (either directly or via subquery) is dead
-- code. Here's why:
--
-- RoofCRM runs a Netflix-style shared-device model:
--   * ONE Google/Supabase auth identity (econoroofing209@gmail.com)
--   * N profiles under that identity (Mario, each crew member, each sales
--     rep, each office manager) — one per person in the company
--   * `active_profile_id` cookie picks which profile is currently "in use"
--
-- `public.users.id` is generated by `crypto.randomUUID()` at profile-create
-- time (`lib/actions/profiles.ts:createProfile`) with NO bridge to
-- `auth.users.id`. That means:
--
--   SELECT * FROM public.users WHERE id = auth.uid()
--
-- ...always returns zero rows. Every policy that gates on this subquery
-- silently evaluates false → returns zero rows to the caller. The app only
-- works in production today because RLS was disabled in the Supabase
-- dashboard on the hot tables (users, jobs, time_entries, activity_log).
-- But that means the migration source-of-truth is out of sync with prod —
-- `supabase db reset` against a clean project would leave the app unable
-- to read anything.
--
-- The real trust boundary for RoofCRM is the SERVER-ACTION LAYER:
-- `lib/auth-helpers.ts:getUserWithCompany` reads the `active_profile_id`
-- cookie, resolves it to a `public.users` row, and every mutation/read is
-- scoped by `.eq('company_id', companyId)` in the query itself. That's the
-- enforcement. RLS is a secondary defensive floor — it denies PostgREST
-- access to unauthenticated clients but does not enforce profile scope.
--
-- This migration adds a PERMISSIVE "authed floor" policy to every RLS-
-- enabled table. PostgreSQL combines permissive policies with OR, so:
--   * If an existing policy passes → row visible (no change in behavior).
--   * If every existing policy evaluates false (the current dead-code
--     situation) → the floor lets authenticated users through, which is
--     what RLS-disabled production already does.
--
-- The broken policies are left in place intentionally. Dropping them would
-- cause churn without benefit; the new floor makes them irrelevant. A
-- future session can come back and do a full sweep if desired.
--
-- SECURITY IMPLICATIONS:
--   * Direct PostgREST queries (bypassing the Next.js server actions) can
--     read everything authenticated users can read — same as production
--     today with RLS disabled. Not a regression.
--   * If Mario ever adds a client-side Supabase query (e.g., a realtime
--     subscription for kanban), that query will see all profiles' data.
--     TODAY there are zero such queries. All reads go through server
--     actions, which do the `.eq('company_id', companyId)` filter.
--   * The long-term "real RLS" fix would be a custom JWT claim that
--     carries `active_profile_id` and policies that read it via
--     `current_setting('request.jwt.claims', true)::json->>'profile_id'`.
--     That's ~4 hours of work and requires middleware changes. Deferred.
-- =============================================================================

BEGIN;

-- For each RLS-enabled table, add a permissive policy that grants any
-- authenticated user full access. `IF NOT EXISTS` is defensive but not
-- strictly needed — running this twice re-creates the policy which is
-- safe because permissive policies OR together.
DO $$
DECLARE
  tbl text;
  tables text[] := ARRAY[
    'users',
    'companies',
    'jobs',
    'time_entries',
    'breaks',
    'activity_log',
    'messages',
    'material_lists',
    'equipment',
    'equipment_logs',
    'certifications',
    'toolbox_talks',
    'toolbox_talk_sessions',
    'toolbox_talk_signoffs',
    'safety_inspections',
    'incidents',
    'crew_unavailability',
    'follow_ups',
    'automation_rules',
    'invoices',
    'invoice_line_items',
    'purchase_orders',
    'supplier_contacts',
    'job_photos',
    'supplement_rounds',
    'subcontractors',
    'job_subcontractors'
  ];
BEGIN
  FOREACH tbl IN ARRAY tables
  LOOP
    -- Only touch tables that actually exist (defensive against future
    -- rename migrations).
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = tbl
    ) THEN
      -- Drop any prior version of our floor policy so this migration is
      -- re-runnable. The broken 001/002/010/012/022/025 policies are
      -- intentionally left in place.
      EXECUTE format('DROP POLICY IF EXISTS "authed_floor" ON public.%I', tbl);
      EXECUTE format(
        'CREATE POLICY "authed_floor" ON public.%I FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL)',
        tbl
      );
    END IF;
  END LOOP;
END $$;

-- Document the trust model on the users table so future devs see it.
COMMENT ON TABLE public.users IS
  'RoofCRM shared-device model: one Supabase auth identity, N profiles. '
  '`public.users.id` is NOT bridged to `auth.users.id` — auth.uid() will '
  'never match any row. Profile selection happens via the active_profile_id '
  'cookie read by lib/auth-helpers.ts:getUserWithCompany. RLS is a defensive '
  'floor; server actions are the real trust boundary. See migration 036.';

COMMIT;
