-- =============================================================================
-- Migration 037: R4 RLS gaps + FK repointing
-- =============================================================================
-- Three fixes from the round-4 audit bundled into one forward-only migration:
--
-- R4-#9 — pricebook_items has no RLS at all. Migration 026 created the table
--         and its two companion tables but never called ENABLE ROW LEVEL
--         SECURITY or created any policies. Any signed-in user could
--         SELECT/UPDATE/DELETE across every company's pricebook.
--
-- R4-#10 — Migration 009 uses `CREATE POLICY IF NOT EXISTS`, which is not
--          standard Postgres syntax in any version I'm aware of. It might
--          have run in a specific Supabase-patched environment but cannot
--          be relied on for a clean `supabase db reset`. Defensively drop
--          + recreate the equipment policies using the DROP POLICY IF
--          EXISTS + CREATE POLICY pattern, which is guaranteed-idempotent
--          and portable.
--
-- R4-#15 — Migration 022 (job_photos.user_id) and 023 (supplement_rounds
--          .created_by) declared their foreign keys against auth.users(id).
--          But every write path in the app passes a public.users.id value
--          (generated by crypto.randomUUID() in createProfile, NOT bridged
--          to auth.users.id). Every insert should have been violating the
--          FK constraint, but prod works — presumably because the constraint
--          was fixed in the dashboard at some point, or was never actually
--          created on this project because of a schema drift. Either way,
--          the source-of-truth migration is wrong. Drop the FK (if it
--          exists) and add the correct one pointing at public.users(id).
--          NOT VALID so existing rows are not re-checked — they may contain
--          orphaned UUIDs from the pre-fix era.
-- =============================================================================

BEGIN;

-- ─── R4-#9: pricebook RLS ────────────────────────────────────────────────────

-- Enable RLS on all three pricebook tables. IF NOT EXISTS semantics: enabling
-- on an already-enabled table is a no-op in Postgres.
DO $$
DECLARE
  tbl text;
  pricebook_tables text[] := ARRAY['pricebook_items', 'pricebook_packages', 'pricebook_package_items'];
BEGIN
  FOREACH tbl IN ARRAY pricebook_tables LOOP
    IF EXISTS (
      SELECT 1 FROM information_schema.tables
      WHERE table_schema = 'public' AND table_name = tbl
    ) THEN
      EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', tbl);
      -- Same defensive-floor pattern as migration 036.
      EXECUTE format('DROP POLICY IF EXISTS "authed_floor" ON public.%I', tbl);
      EXECUTE format(
        'CREATE POLICY "authed_floor" ON public.%I FOR ALL USING (auth.uid() IS NOT NULL) WITH CHECK (auth.uid() IS NOT NULL)',
        tbl
      );
    END IF;
  END LOOP;
END $$;

-- ─── R4-#10: defensively re-create equipment policies ───────────────────────

-- Migration 009 may or may not have landed cleanly on every environment.
-- Drop any prior version and re-create from scratch with standard syntax.
DROP POLICY IF EXISTS "equipment_read"      ON public.equipment;
DROP POLICY IF EXISTS "equipment_write"     ON public.equipment;
DROP POLICY IF EXISTS "equipment_logs_read" ON public.equipment_logs;
DROP POLICY IF EXISTS "equipment_logs_write" ON public.equipment_logs;

CREATE POLICY "equipment_read"
  ON public.equipment
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "equipment_write"
  ON public.equipment
  FOR ALL
  USING (auth.uid() IS NOT NULL)
  WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "equipment_logs_read"
  ON public.equipment_logs
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "equipment_logs_write"
  ON public.equipment_logs
  FOR INSERT
  WITH CHECK (auth.uid() IS NOT NULL);

-- ─── R4-#15: FK repointing to public.users ──────────────────────────────────

-- Drop any FK that points at auth.users from job_photos.user_id. The
-- constraint name is whatever Postgres assigned at creation time, so look
-- it up from information_schema and drop by actual name.
DO $$
DECLARE
  cons_name text;
BEGIN
  FOR cons_name IN
    SELECT conname FROM pg_constraint
    WHERE conrelid = 'public.job_photos'::regclass
      AND contype = 'f'
      AND confrelid = 'auth.users'::regclass
  LOOP
    EXECUTE format('ALTER TABLE public.job_photos DROP CONSTRAINT %I', cons_name);
  END LOOP;
EXCEPTION
  WHEN undefined_table THEN
    -- job_photos doesn't exist yet (migration 022 hasn't run) — skip.
    NULL;
END $$;

-- Add the correct FK pointing at public.users. NOT VALID so any existing
-- rows with orphaned user_ids don't block the migration. New inserts will
-- still be checked against the constraint.
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'job_photos'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.job_photos'::regclass
      AND contype = 'f'
      AND confrelid = 'public.users'::regclass
      AND conname = 'job_photos_user_id_fkey'
  ) THEN
    ALTER TABLE public.job_photos
      ADD CONSTRAINT job_photos_user_id_fkey
      FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE SET NULL
      NOT VALID;
  END IF;
END $$;

-- Same surgery for supplement_rounds.created_by.
DO $$
DECLARE
  cons_name text;
BEGIN
  FOR cons_name IN
    SELECT conname FROM pg_constraint
    WHERE conrelid = 'public.supplement_rounds'::regclass
      AND contype = 'f'
      AND confrelid = 'auth.users'::regclass
  LOOP
    EXECUTE format('ALTER TABLE public.supplement_rounds DROP CONSTRAINT %I', cons_name);
  END LOOP;
EXCEPTION
  WHEN undefined_table THEN
    NULL;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'supplement_rounds'
  ) AND NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conrelid = 'public.supplement_rounds'::regclass
      AND contype = 'f'
      AND confrelid = 'public.users'::regclass
      AND conname = 'supplement_rounds_created_by_fkey'
  ) THEN
    ALTER TABLE public.supplement_rounds
      ADD CONSTRAINT supplement_rounds_created_by_fkey
      FOREIGN KEY (created_by) REFERENCES public.users(id) ON DELETE SET NULL
      NOT VALID;
  END IF;
END $$;

COMMIT;
