-- =============================================================================
-- Migration 040: Declare claim-documents bucket + fix dead clock-photos policy
-- =============================================================================
-- Two related storage fixes from the round-5 audit:
--
-- R5-#5 — `claim-documents` bucket was referenced in
--         `components/insurance/claim-workflow.tsx` and
--         `lib/actions/insurance.ts` but NEVER created in any migration.
--         Either prod uploads fail silently in a try/catch, or the bucket
--         was manually created in the Supabase dashboard — in which case
--         it has default policies and no tenant scoping. Insurance claim
--         documents (Xactimate scopes, adjuster estimates, deductible
--         receipts, approval letters) are highly sensitive. This migration
--         declares the bucket explicitly with the same defensive-floor
--         pattern used by the other private buckets:
--           - public = false
--           - RLS enabled
--           - INSERT requires auth
--           - SELECT requires auth (server-action layer enforces company
--             scope, documented in architecture.md §1.4)
--
-- R5-#9 — `clock_photos_read_manager` policy in migration 002 checks
--         `role = 'manager'` but the role enum was simplified to
--         {owner, office_manager, sales, crew}. No row ever has
--         `role = 'manager'`, so supervisors cannot see their crew's
--         clock-in photos via this policy — only the `clock_photos_read_own`
--         path works (crew sees own photos, supervisors see nothing).
--         Combined with the R5-#4 private-bucket fix, proof-of-presence is
--         now actually broken (crew uploads work, but supervisors can't
--         verify). Drop and recreate with the correct role names.
--
-- Defensive: all operations use IF NOT EXISTS / DROP IF EXISTS / UPSERT
-- semantics so the migration is re-runnable.
-- =============================================================================

BEGIN;

-- ─── R5-#5: declare claim-documents bucket ──────────────────────────────────

-- INSERT IF NOT EXISTS via ON CONFLICT. If the bucket was previously
-- created manually in the dashboard, this is a no-op; if it's fresh,
-- this creates it with the correct private flag.
INSERT INTO storage.buckets (id, name, public)
VALUES ('claim-documents', 'claim-documents', false)
ON CONFLICT (id) DO UPDATE
SET public = EXCLUDED.public;

-- Drop any prior policies and recreate with the defensive floor.
DROP POLICY IF EXISTS "claim_documents_upload" ON storage.objects;
DROP POLICY IF EXISTS "claim_documents_read"   ON storage.objects;

CREATE POLICY "claim_documents_upload"
  ON storage.objects
  FOR INSERT
  WITH CHECK (bucket_id = 'claim-documents' AND auth.role() = 'authenticated');

CREATE POLICY "claim_documents_read"
  ON storage.objects
  FOR SELECT
  USING (bucket_id = 'claim-documents' AND auth.uid() IS NOT NULL);

-- ─── R5-#9: repair clock-photos read policies to match trust model ────────

-- The original clock_photos_read_manager policy from migration 002
-- checked `role = 'manager'` which no longer exists in the role enum.
-- But even fixing the role name to {owner, office_manager} wouldn't
-- work — the policy does
--   EXISTS (SELECT 1 FROM users WHERE id = auth.uid() ...)
-- and under RoofCRM's shared-device model, `public.users.id` is
-- generated by crypto.randomUUID() with NO bridge to auth.users.id, so
-- the subquery ALWAYS returns empty. This is the same dead-policy
-- pattern documented in R4-#1 and addressed for public.* tables by
-- migration 036's authed_floor.
--
-- The defensive floor for storage.objects needs to be declared per-
-- bucket (storage RLS doesn't inherit from 036). Drop all existing
-- clock-photos policies and replace with a single floor: authenticated
-- users can read any clock-in photo. Server-action layer enforces
-- per-job access by selecting via time_entries → jobs → company_id
-- before handing the photo URL to a client. Same pattern as the
-- estimates bucket in migration 039.
DROP POLICY IF EXISTS "clock_photos_read_own"     ON storage.objects;
DROP POLICY IF EXISTS "clock_photos_read_manager" ON storage.objects;

CREATE POLICY "clock_photos_read"
  ON storage.objects
  FOR SELECT
  USING (bucket_id = 'clock-photos' AND auth.uid() IS NOT NULL);

COMMIT;
